ConfigPath = './config'
ConfigPathV2 = './pkg/v2/toml'
GlobalPrefix = 'config'
ConsulProtocol = 'http'
ConsulHost = 'localhost'
ConsulPort = 8500
IsReset = true
FailLimit = 30
FailWaitTime = 3
AcceptablePropertyExtensions = ['.toml','.yaml', '.yml', '.properties']
YamlExtensions = ['.yaml','.yml']
TomlExtensions = ['.toml']